// Code generated by protoc-gen-go. DO NOT EDIT.
// source: person.proto

/*
Package person is a generated protocol buffer package.

It is generated from these files:
	person.proto

It has these top-level messages:
	SpeakMessage
	ColorMessage
	PersonMessage
	Void
*/
package person

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SpeakMessage struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *SpeakMessage) Reset()                    { *m = SpeakMessage{} }
func (m *SpeakMessage) String() string            { return proto.CompactTextString(m) }
func (*SpeakMessage) ProtoMessage()               {}
func (*SpeakMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SpeakMessage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ColorMessage struct {
	Color string `protobuf:"bytes,1,opt,name=color" json:"color,omitempty"`
}

func (m *ColorMessage) Reset()                    { *m = ColorMessage{} }
func (m *ColorMessage) String() string            { return proto.CompactTextString(m) }
func (*ColorMessage) ProtoMessage()               {}
func (*ColorMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ColorMessage) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type PersonMessage struct {
	Name      string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	EyeColor  string `protobuf:"bytes,2,opt,name=eyeColor" json:"eyeColor,omitempty"`
	HairColor string `protobuf:"bytes,3,opt,name=hairColor" json:"hairColor,omitempty"`
	Height    uint32 `protobuf:"varint,4,opt,name=height" json:"height,omitempty"`
}

func (m *PersonMessage) Reset()                    { *m = PersonMessage{} }
func (m *PersonMessage) String() string            { return proto.CompactTextString(m) }
func (*PersonMessage) ProtoMessage()               {}
func (*PersonMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PersonMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonMessage) GetEyeColor() string {
	if m != nil {
		return m.EyeColor
	}
	return ""
}

func (m *PersonMessage) GetHairColor() string {
	if m != nil {
		return m.HairColor
	}
	return ""
}

func (m *PersonMessage) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*SpeakMessage)(nil), "person.SpeakMessage")
	proto.RegisterType((*ColorMessage)(nil), "person.ColorMessage")
	proto.RegisterType((*PersonMessage)(nil), "person.PersonMessage")
	proto.RegisterType((*Void)(nil), "person.Void")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PersonService service

type PersonServiceClient interface {
	Speak(ctx context.Context, in *Void, opts ...grpc.CallOption) (*SpeakMessage, error)
	DyeHair(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Void, error)
	GetPerson(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PersonMessage, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) Speak(ctx context.Context, in *Void, opts ...grpc.CallOption) (*SpeakMessage, error) {
	out := new(SpeakMessage)
	err := grpc.Invoke(ctx, "/person.PersonService/Speak", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) DyeHair(ctx context.Context, in *ColorMessage, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/person.PersonService/DyeHair", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *personServiceClient) GetPerson(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PersonMessage, error) {
	out := new(PersonMessage)
	err := grpc.Invoke(ctx, "/person.PersonService/GetPerson", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PersonService service

type PersonServiceServer interface {
	Speak(context.Context, *Void) (*SpeakMessage, error)
	DyeHair(context.Context, *ColorMessage) (*Void, error)
	GetPerson(context.Context, *Void) (*PersonMessage, error)
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_Speak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).Speak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.PersonService/Speak",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).Speak(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_DyeHair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ColorMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).DyeHair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.PersonService/DyeHair",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).DyeHair(ctx, req.(*ColorMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _PersonService_GetPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).GetPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/person.PersonService/GetPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).GetPerson(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "person.PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Speak",
			Handler:    _PersonService_Speak_Handler,
		},
		{
			MethodName: "DyeHair",
			Handler:    _PersonService_DyeHair_Handler,
		},
		{
			MethodName: "GetPerson",
			Handler:    _PersonService_GetPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "person.proto",
}

func init() { proto.RegisterFile("person.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x59, 0x4d, 0x57, 0x33, 0xa4, 0x97, 0xa1, 0x4a, 0x08, 0x1e, 0x4a, 0xf0, 0x50, 0x10,
	0x8b, 0xe8, 0x23, 0x28, 0xe8, 0x45, 0x90, 0x16, 0xbc, 0xaf, 0x75, 0x68, 0x16, 0x63, 0x36, 0x6c,
	0xfe, 0x40, 0x1e, 0xc6, 0x77, 0x95, 0xcc, 0x66, 0x63, 0xe2, 0x6d, 0x7f, 0x3b, 0x3f, 0xbe, 0xe1,
	0x1b, 0x88, 0x4a, 0xb2, 0x95, 0x29, 0xb6, 0xa5, 0x35, 0xb5, 0x41, 0xe9, 0x28, 0xbd, 0x86, 0x68,
	0x5f, 0x92, 0xfa, 0x7a, 0xa5, 0xaa, 0x52, 0x47, 0xc2, 0x15, 0x2c, 0x5a, 0x95, 0x37, 0x14, 0x8b,
	0xb5, 0xd8, 0x84, 0x3b, 0x07, 0xbd, 0xf5, 0x68, 0x72, 0x63, 0x27, 0xd6, 0xa1, 0x67, 0x6f, 0x31,
	0xa4, 0x0d, 0x2c, 0xdf, 0x38, 0xd5, 0x6b, 0x08, 0x41, 0xa1, 0xbe, 0x7d, 0x16, 0xbf, 0x31, 0x81,
	0x73, 0xea, 0x88, 0xd3, 0xe2, 0x13, 0xfe, 0x1f, 0x19, 0xaf, 0x20, 0xcc, 0x94, 0xb6, 0x6e, 0x78,
	0xca, 0xc3, 0xbf, 0x0f, 0xbc, 0x04, 0x99, 0x91, 0x3e, 0x66, 0x75, 0x1c, 0xac, 0xc5, 0x66, 0xb9,
	0x1b, 0x28, 0x95, 0x10, 0xbc, 0x1b, 0xfd, 0x79, 0xff, 0x23, 0xfc, 0xfe, 0x3d, 0xd9, 0x56, 0x1f,
	0x08, 0x6f, 0x60, 0xc1, 0xe5, 0x30, 0xda, 0x0e, 0xe5, 0x7b, 0x31, 0x59, 0x79, 0x9a, 0x35, 0xbf,
	0x85, 0xb3, 0xa7, 0x8e, 0x5e, 0x94, 0xb6, 0x38, 0x0a, 0xd3, 0xd2, 0xc9, 0x2c, 0x04, 0xef, 0x20,
	0x7c, 0xa6, 0xda, 0xed, 0xfb, 0x97, 0x7f, 0xe1, 0x69, 0x76, 0x8d, 0x0f, 0xc9, 0x97, 0x7f, 0xf8,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0xb0, 0xd4, 0x80, 0xd3, 0x89, 0x01, 0x00, 0x00,
}
